name: Setup go-web-infra
description: Checkout and setup go-web-infra dependency

runs:
  using: composite
  steps:
    - name: Checkout go-web-infra
      uses: actions/checkout@v6
      with:
        repository: jborkows/k3sfun
        path: go-web-infra
        sparse-checkout: |
          go-web-infra
        sparse-checkout-cone-mode: false

    - name: Fix go.mod
      shell: bash
      run: |
        sed -i 's|../go-web-infra|./go-web-infra|' go.mod
        cat go.mod
