apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    email: EMAIL
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-key
    solvers:
    - dns01:
        cloudflare:
          email: EMAIL
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: CERTNAME
  namespace: kube-system
spec:
  secretName: CERTNAME
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: '*.DOMAIN'
  dnsNames:
    - '*.DOMAIN'
    - DOMAIN
