---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: external-pv
spec:
  capacity:
    storage: 1424Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/external
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: external-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1424Gi
---
