---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-nginx-config
  namespace: applications
data:
  nginx.conf: |
    worker_processes 1;
    error_log /dev/stderr warn;
    pid /tmp/nginx.pid;

    events {
        worker_connections 256;
    }

    http {
        access_log /dev/stdout;
        client_body_temp_path /tmp/client_body;
        proxy_temp_path /tmp/proxy;
        fastcgi_temp_path /tmp/fastcgi;
        uwsgi_temp_path /tmp/uwsgi;
        scgi_temp_path /tmp/scgi;

        # Allow large file uploads (10GB)
        client_max_body_size 10G;
        proxy_request_buffering off;
        client_body_buffer_size 512k;

        upstream oauth2_proxy {
            server 127.0.0.1:4180;
        }

        upstream filebrowser_direct {
            server 127.0.0.1:8080;
        }

        upstream filebrowser_admin {
            server 127.0.0.1:8081;
        }

        # Main filebrowser - OIDC protected only (no fallback since noauth)
        server {
            listen 8000;

            location /healthz {
                return 200 'OK';
                add_header Content-Type text/plain;
            }

            location / {
                # Always go through oauth2-proxy - no fallback since filebrowser uses noauth
                proxy_connect_timeout 5s;
                proxy_read_timeout 30s;
                proxy_send_timeout 30s;
                
                proxy_pass http://oauth2_proxy;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }

        # Admin filebrowser - direct access with filebrowser's own auth
        server {
            listen 8001;

            location /healthz {
                return 200 'OK';
                add_header Content-Type text/plain;
            }

            location / {
                proxy_pass http://filebrowser_admin;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }

  # Filebrowser main settings - proxy auth using OIDC email header
  settings.json: |
    {
      "port": 8080,
      "baseURL": "",
      "address": "0.0.0.0",
      "log": "stdout",
      "database": "/database/filebrowser.db",
      "root": "/srv"
    }

  # Filebrowser admin settings - with login for user management
  # Uses separate database to avoid SQLite lock conflicts
  settings-admin.json: |
    {
      "port": 8081,
      "baseURL": "",
      "address": "0.0.0.0",
      "log": "stdout",
      "database": "/database/filebrowser-admin.db",
      "root": "/srv"
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      initContainers:
        # Initialize filebrowser database with proxy auth
        - name: filebrowser-init
          image: alpine
          command:
            - sh
            - -c
            - |
              # Download filebrowser binary
              wget -qO /tmp/filebrowser.tar.gz https://github.com/filebrowser/filebrowser/releases/download/v2.31.2/linux-amd64-filebrowser.tar.gz
              tar -xzf /tmp/filebrowser.tar.gz -C /tmp
              chmod +x /tmp/filebrowser
              
              # Initialize database if not exists
              if [ ! -f /database/filebrowser.db ]; then
                echo "Initializing new database..."
                /tmp/filebrowser config init --database=/database/filebrowser.db
              fi
              
              # Set proxy auth method
              echo "Setting proxy auth method..."
              /tmp/filebrowser config set \
                --auth.method=proxy \
                --auth.header=X-Forwarded-Email \
                --database=/database/filebrowser.db
              
              # Fix permissions - filebrowser image runs as UID 1000
              chown -R 1000:1000 /database
              chmod 755 /database
              chmod 644 /database/*.db 2>/dev/null || true
              
              echo "Init complete"
          volumeMounts:
            - name: fd-db
              mountPath: /database
      containers:
        # Nginx proxy - entry point that handles failover
        - name: nginx-proxy
          image: nginx:alpine
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 8001
              name: admin
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-tmp
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 32Mi

        # OAuth2 Proxy for OIDC authentication - runs native binary directly
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
          args:
            - --http-address=0.0.0.0:4180
            - --upstream=http://127.0.0.1:8080
            - --provider=oidc
            - --email-domain=*
            - --cookie-secure=true
            - --cookie-samesite=lax
            - --cookie-refresh=1h
            - --cookie-expire=24h
            - --pass-access-token=true
            - --set-xauthrequest=true
            - --skip-provider-button=true
            - --silence-ping-logging=true
            - --code-challenge-method=S256
            - --pass-user-headers=true
            - --set-authorization-header=true
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: filebrowser-oidc
                  key: OIDC_CLIENT_ID
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: filebrowser-oidc
                  key: OIDC_CLIENT_SECRET
            - name: OAUTH2_PROXY_OIDC_ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: filebrowser-oidc
                  key: OIDC_ISSUER_URL
            - name: OAUTH2_PROXY_REDIRECT_URL
              value: "https://filebrowser.DOMAIN/oauth2/callback"
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: filebrowser-oidc
                  key: COOKIE_SECRET
          ports:
            - containerPort: 4180
          livenessProbe:
            httpGet:
              path: /ping
              port: 4180
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: 4180
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi

        # Main filebrowser container - OIDC protected with proxy auth
        - name: filebrowser
          image: filebrowser/filebrowser
          volumeMounts:
            - name: files
              mountPath: /srv
            - name: fd-db
              mountPath: /database
            - name: filebrowser-settings
              mountPath: /config/settings.json
              subPath: settings.json
          ports:
            - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi

        # Admin filebrowser container - with internal login for user management
        - name: filebrowser-admin
          image: filebrowser/filebrowser
          volumeMounts:
            - name: files
              mountPath: /srv
            - name: fd-db
              mountPath: /database
            - name: filebrowser-admin-settings
              mountPath: /config/settings.json
              subPath: settings-admin.json
          ports:
            - containerPort: 8081
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi

      volumes:
        - name: files
          hostPath:
            path: /mnt/external/drive
            type: Directory
        - name: fd-db
          hostPath:
            path: /mnt/external/filebrowser-db
            type: DirectoryOrCreate
        - name: nginx-config
          configMap:
            name: filebrowser-nginx-config
            defaultMode: 0755
        - name: nginx-tmp
          emptyDir: {}
        - name: filebrowser-settings
          configMap:
            name: filebrowser-nginx-config
            items:
              - key: settings.json
                path: settings.json
        - name: filebrowser-admin-settings
          configMap:
            name: filebrowser-nginx-config
            items:
              - key: settings-admin.json
                path: settings-admin.json
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  namespace: applications
spec:
  selector:
    app: filebrowser
  ports:
    - port: 80
      targetPort: 8000
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser-admin
  namespace: applications
spec:
  selector:
    app: filebrowser
  ports:
    - port: 80
      targetPort: 8001
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filebrowser-ingress
  namespace: applications
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # Allow large file uploads (10GB)
    traefik.ingress.kubernetes.io/buffering: |
      maxRequestBodyBytes: 10737418240
      memRequestBodyBytes: 10485760
spec:
  rules:
    - host: filebrowser.DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: filebrowser
                port:
                  number: 80
  tls:
    - hosts:
        - filebrowser.DOMAIN
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filebrowser-admin-ingress
  namespace: applications
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # Allow large file uploads (10GB)
    traefik.ingress.kubernetes.io/buffering: |
      maxRequestBodyBytes: 10737418240
      memRequestBodyBytes: 10485760
spec:
  rules:
    - host: filebrowser-admin.DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: filebrowser-admin
                port:
                  number: 80
  tls:
    - hosts:
        - filebrowser-admin.DOMAIN
