---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser
        volumeMounts:
        - name: files
          mountPath: /srv
        - name: fd-db
          mountPath: /database
        ports:
        - containerPort: 80
      volumes:
      - name: files
        hostPath:
          path: /mnt/external/drive
          type: Directory
      - name: fd-db
        hostPath:
          path: /mnt/external/filebrowser-db
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  namespace: applications
spec:
  selector:
    app: filebrowser
  ports:
  - port: 80
    targetPort: 80
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filebrowserr-ingress
  namespace: applications
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
  - host: filebrowser.DOMAIN
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: filebrowser
            port:
              number: 80
  tls:
  - hosts:
    - filebrowser.DOMAIN


