apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: traefik
  repo: https://helm.traefik.io/traefik
  targetNamespace: kube-system
  set:
    additionalArguments[0]: "--log.level=DEBUG"
  valuesContent: |-
    api:
      dashboard: true
    
    ports:
      web:
        port: 8000
        expose:
          default: true
        exposedPort: 80
        protocol: TCP
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
      websecure:
        port: 8443
        expose:
          default: true
        exposedPort: 443
        protocol: TCP
        http:
          tls:
            enabled: true
        http3:
          enabled: true
          advertisedPort: 443
    
    providers:
      kubernetesIngress:
        enabled: true
        publishedService:
          enabled: true
      kubernetesCRD:
        enabled: true
    
    service:
      enabled: true
      single: false
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.0.124
        metallb.universe.tf/allow-shared-ip: "traefik-shared"
